package org.goosenvi.exercises.model.document;

public class Document {

    /**
     * The Document primary key identifier generated by the database.
     */
    private Long id = null;

    /**
     * The Document identifier.
     */
    private String docId = null;

    /**
     * The document name.
     */
    private String name = "";

    /**
     * The informative description of the document.
     */
    private String description = "";

    /**
     * The Document path.
     */
    private String path = "";

    /**
     * The default constructor.
     */
    public Document() {
        super();
    }

    /**
     * The constructor using all the fields.
     *
     * @param id          the unique id in the database
     * @param docId       the document identifier
     * @param name        the document name
     * @param description an informative description of the document
     * @param path        the path to the document
     */
    public Document(Long id, String docId, String name, String description, String path) {
        super();
        this.id = id;
        this.docId = docId;
        this.name = name;
        this.description = description;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocId() {
        return docId;
    }

    public void setDocId(String docId) {
        this.docId = docId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
}