package org.goosenvi.exercises.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * The persistent Note class that contains information about a Note.
 *
 */
@Entity
@Table(name = "NOTE")
public class Note {

    /**
     * The Note primary key identifier generated by the database.
     */
    @SequenceGenerator(name = "note_id", sequenceName = "public.note_id_seq_pg", allocationSize = 3)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "note_id")
    @Id
    @Column(name = "PK_ID")
    private Long id = null;

    /**
     * The Note identifier.
     */
    @Column(name = "NOTE_ID", unique = true)
    private Long noteId = null;

    /**
     * The Note header.
     */
    @Column(name = "HEADER")
    private String header = "";

    /**
     * The Note body content.
     */
    @Column(name = "BODY")
    private String body = "";

    /**
     * A comment about the Note.
     */
    @Column(name = "COMMENT")
    private String comment = "";

    /**
     * The default constructor.
     */
    public Note() {
        super();
    }

    /**
     * The constructor using only a few fields.
     *
     * @param noteId the note id
     * @param header the note header
     */
    public Note(Long noteId, String header) {
        super();
        this.noteId = noteId;
        this.header = header;
    }

    /**
     * The Note constructor using all the fields.
     *
     * @param id      the Note id
     * @param header  the Note header
     * @param body    the Note body content
     * @param comment a comment about the Note
     */
    public Note(Long id, Long noteId, String header, String body, String comment) {
        super();
        this.id = id;
        this.noteId = noteId;
        this.header = header;
        this.body = body;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNoteId() {
        return noteId;
    }

    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Attn: Do not use the prefix get on the method name it will be returned in the
     * JSON response.
     *
     * @return the Note information in a concatenated string format
     */
    public String noteInformation() {
        return "PK Id: " + getId() + ", NoteId: " + getNoteId() + ", Header: " + getHeader() + ", Body: " + getBody()
                + ", Comment: " + getComment();
    }
}